# WebSocket 연결 요청일 때, Upgrade 헤더 전달
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server{
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # API 요청은 Spring Boot로 전달
    location /api/ {
        proxy_pass http://backend:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # SockJS의 HTTP 요청과 WebSocket 연결을 모두 전달
    location /ws-security {
        proxy_pass http://backend:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 3600s;
    }

    # React 정적 파일 제공
    # 파일이 없는 화면 경로는 React가 처리하도록 index.html 반환
    location / {
        try_files $uri $uri/ /index.html;
    }
}